title: Busta Paga - Professionale
description: Documentazione di base dell'applicazione Busta Paga - Professionale
theme: just-the-docs

url: https://luigivezzoso.github.io/bustapagaprofessionale/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
